import { useEffect, useState } from "react";
import { Grid } from "@mui/material";
import AssessmentRoundedIcon from "@mui/icons-material/AssessmentRounded";
import CancelRoundedIcon from "@mui/icons-material/CancelRounded";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";
import PercentRoundedIcon from "@mui/icons-material/PercentRounded";
import PageContainer from "../../components/Common/PageContainer";
import SectionHeader from "../../components/Common/SectionHeader";
import LoadingState from "../../components/Common/LoadingState";
import ErrorState from "../../components/Common/ErrorState";
import MetricCard from "../../components/Analytics/MetricCard";
import DefaultChart from "../../components/Analytics/DefaultChart";
import RiskDistributionChart from "../../components/Analytics/RiskDistributionChart";
import RiskProbabilityDistributionChart from "../../components/Analytics/RiskProbabilityDistributionChart";
import FeatureOverviewChart from "../../components/Analytics/FeatureOverviewChart";
import ModelInfoCard from "../../components/Analytics/ModelInfoCard";
import { getAnalytics } from "../../services/api";
import { formatNumber, formatPercent } from "../../utils/formatters";

const Analytics = () => {
  const [data, setData] = useState(null);
  const [status, setStatus] = useState("loading"); // loading | success | error

  const fetchAnalytics = async () => {
    try {
      const result = await getAnalytics();
      setData(result);
      setStatus("success");
    } catch {
      setStatus("error");
    }
  };

  const retryLoadAnalytics = () => {
    setStatus("loading");
    fetchAnalytics();
  };

  useEffect(() => {
    (async () => {
      await fetchAnalytics();
    })();
  }, []);

  return (
    <PageContainer>
      <SectionHeader
        eyebrow="Analytics"
        title="Analytics Dashboard"
        subtitle="Aggregate view of predictions generated by the LoanGuard model."
      />

      {status === "loading" && <LoadingState message="Loading analytics..." minHeight={360} />}

      {status === "error" && (
        <ErrorState
          message="Unable to load analytics. Please try again."
          onAction={retryLoadAnalytics}
        />
      )}

      {status === "success" && data && (
        <>
          <Grid container spacing={3} sx={{ mb: 4 }}>
            <Grid size={{ xs: 6, md: 3 }}>
              <MetricCard
                icon={AssessmentRoundedIcon}
                label="Total Applications"
                value={formatNumber(data.totals.totalApplications)}
              />
            </Grid>
            <Grid size={{ xs: 6, md: 3 }}>
              <MetricCard
                icon={CancelRoundedIcon}
                label="Default Predictions"
                value={formatNumber(data.totals.defaultPredictions)}
                accentColor="error.main"
              />
            </Grid>
            <Grid size={{ xs: 6, md: 3 }}>
              <MetricCard
                icon={CheckCircleRoundedIcon}
                label="No Default Predictions"
                value={formatNumber(data.totals.noDefaultPredictions)}
                accentColor="success.main"
              />
            </Grid>
            <Grid size={{ xs: 6, md: 3 }}>
              <MetricCard
                icon={PercentRoundedIcon}
                label="Average Risk Probability"
                value={formatPercent(data.totals.averageRiskProbability)}
              />
            </Grid>
          </Grid>

          <Grid container spacing={3} sx={{ mb: 3 }}>
            <Grid size={{ xs: 12, md: 6 }}>
              <DefaultChart data={data.defaultVsNoDefault} />
            </Grid>
            <Grid size={{ xs: 12, md: 6 }}>
              <RiskDistributionChart data={data.riskDistribution} />
            </Grid>
          </Grid>

          <Grid container spacing={3} sx={{ mb: 3 }}>
            <Grid size={{ xs: 12, md: 6 }}>
              <RiskProbabilityDistributionChart data={data.riskProbabilityDistribution} />
            </Grid>
            <Grid size={{ xs: 12, md: 6 }}>
              <FeatureOverviewChart data={data.featureOverview} />
            </Grid>
          </Grid>

          <ModelInfoCard model={data.model} />
        </>
      )}
    </PageContainer>
  );
};

export default Analytics;
